### PR TITLE
Make it possible to show rain volume

### PR DESCRIPTION
**Pull request by cwitting**
This simply makes it possible to switch between showing Posibility of Precipitation (PoP) and rain volume in mm on the graph

### CODE REVIEW

**Comment by lmarzen** [comment]
I like this addition.
I have a few suggestions.
Some people may wish to change the unit. Particularly, I would advocate for an option to have the choice between mm, inches, and cm.
Second thing to note is that OpenWeatherMap has separate fields for rainfall and snowfall. I think we should add these fields so they are representative of the precipitation regardless of the season someone may be experiencing,

Let me know what you think?

**Comment by cwitting** [comment]
Yes, I agree. I have added another commit which makes it possible to specify the unit, as well as combining snow and rain precipitation.

**Comment by lmarzen** [comment]
I have been busy with school work. I will try to get this merged over the thanksgiving holiday.

**Comment by lmarzen** [comment]
Overall this is a great contribution. Thank you.
I added automatic precision adjustments for the y-axis ticks to reduce the likelihood that the rainfall will run off the screen.

**Review by lmarzen — APPROVED** [review]

**Pull request merged**
